// <auto-generated />
using System;
using COE000.Portal.NomeProjeto.Reposity.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COE000.Portal.NomeProjeto.Migrations.DataBase
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220610162558_alterDataBase")]
    partial class alterDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.HashModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ConfigCode")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TB_UserConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
