// <auto-generated />
using System;
using COE000.Portal.NomeProjeto.Reposity.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COE000.Portal.NomeProjeto.Migrations.DataBase
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Areas.Identity.Data.IncriseUserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Gender");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.EnvironmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnvCode");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.HasKey("Id");

                    b.ToTable("TB_Environment", (string)null);
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.FunctionTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FunctionTypeModel");
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.HashModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ConfigCode")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TB_UserConfig", (string)null);
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.HistoricModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("LegacyCode")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FunctionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("FunctionCode");

                    b.Property<string>("Observation")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)")
                        .HasColumnName("UserCode");

                    b.HasKey("Id");

                    b.HasIndex("FunctionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_Legacy", (string)null);
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.RpaCredentialModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CredentionCode")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int")
                        .HasColumnName("EnvCode");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR(80)");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("TB_RpaCredential", (string)null);
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.HistoricModel", b =>
                {
                    b.HasOne("COE000.Portal.NomeProjeto.Models.Entity.FunctionTypeModel", "FunctionType")
                        .WithMany("HistoricGroup")
                        .HasForeignKey("FunctionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COE000.Portal.NomeProjeto.Areas.Identity.Data.IncriseUserModel", "User")
                        .WithMany("HistoricCollection")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.RpaCredentialModel", b =>
                {
                    b.HasOne("COE000.Portal.NomeProjeto.Models.Entity.EnvironmentModel", "Environment")
                        .WithMany("RpaCredentiaGroup")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Areas.Identity.Data.IncriseUserModel", b =>
                {
                    b.Navigation("HistoricCollection");
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.EnvironmentModel", b =>
                {
                    b.Navigation("RpaCredentiaGroup");
                });

            modelBuilder.Entity("COE000.Portal.NomeProjeto.Models.Entity.FunctionTypeModel", b =>
                {
                    b.Navigation("HistoricGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
